### ISSUE TITLE
Top-Level 'name' attribute regex Docker Compose Error

### ISSUE THREAD

**Issue by MimikoM** [Duinrahaic/ScheduleBot#6]
I might just be doing something wrong, but from what I can find it seems like there may be an issue with most-recent Docker Compose versioning that is preventing launch of the provided container. 

----

I kept everything out-of-the-box, so using internal database with default passwords. No changes in docker-compose.yaml, only change in .env is to add my bot token. When running `docker-compose up -d` I get this 'name' attribute regex error:

![image](https://github.com/Duinrahaic/ScheduleBot/assets/106928743/1cb963e1-6a2f-4ffe-bfc8-52b348380c62)

Researching that error I came across [this StackOverflow post](https://stackoverflow.com/questions/73427249/name-does-not-match-any-of-the-regexes-x-while-trying-to-set-the-project), which seems to suggest the top-level 'name' attribute is no longer supported.

That post notes a difference between `docker compose` and `docker-compose` (notice hyphen), so I tried launching with `docker compose up -d` instead, which results in an "invalid reference format" error:

![image](https://github.com/Duinrahaic/ScheduleBot/assets/106928743/f1ce83e4-3cf1-4e3c-bb2d-5b641836d43a)

The StackOverflow also implies that leaving container name unspecified would result in it inheriting the directory name, or that a workaround of setting a **$COMPOSE_PROJECT_NAME** environment variable can be used to inherit the container name. I also tried commenting-out the top-level 'name' in docker-compose.yaml and defining that environment variable (set to _schedule-bot_ ) . Upon doing so I seem to get the same error with `docker-compose` that `docker compose` gives with the name attribute in place:

![image](https://github.com/Duinrahaic/ScheduleBot/assets/106928743/f58ba14c-8c22-4103-acaa-c82236fd04da)

Unfortunately my docker skills aren't up to par to really understand what the 'invalid reference format' error is caused by. Quick search seems to suggest it's related to a call to `pwd` command when a directory has a space in it, but there shouldn't be any such directories. Only thing potentially "odd" about my setup is that my username has an underscore, but I doubt that matters.,, I'd think this is an error internal to the container?

Or maybe we really do need to use the newer `docker-compose`, but it's reliant on that top-level 'name' attribute for something, so removing/workaround to avoid that are breaking something internally?

------

Environment details:

Fresh install of Ubuntu 22.04 on a GCP virtual machine:
Ubuntu 22.04.2 LTS (GNU/Linux 5.19.0-1027-gcp x86_64)

Docker, docker compose, and docker-compose versions:
![image](https://github.com/Duinrahaic/ScheduleBot/assets/106928743/06a52841-87d1-4349-94eb-a118ce875ae7)
![image](https://github.com/Duinrahaic/ScheduleBot/assets/106928743/c34e41c4-b8e4-4997-a8b7-b4b404e08898)

**Comment by MimikoM** [comment]
Oh, also just fyi the Discord invite in your README is expired. Would have checked on there for potential troubleshooting but was unable to access.

**Comment by Duinrahaic** [comment]
After reviewing the issue and testing in an ubuntu linux environment I found that my stock configuration of the YAML file did not resolve my image name correctly.

I initially tested and was able to resolve the image name duinrahaic\schedulebot:latest however it does not resolve correctly in a linux environment. 

In a linux environment it should be duinrahaic/schedulebot:latest

![image](https://github.com/Duinrahaic/ScheduleBot/assets/7483431/4ba1b84d-5e76-405d-88e7-c93a3e84c3d8)


I'll make a pull and correct this issue. However in the mean time, a correct Compose file should look like this: 

`version: '3.9'
name: schedule-bot
services:
    db:
        hostname: scheduleBot-db
        image: mysql:8.0.26
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            MYSQL_DATABASE: '${MYSQL_DB}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PW}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_USER_PW}'
        ports:
            - '3306:3306'
        volumes:
            - db:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - scheduleBot-network
        env_file:
            - .env
        healthcheck:
            test: ["CMD", "mysqladmin", "-u {MYSQL_USER}", "-p {MYSQL_USER_PW}",  "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 3
    bot:
        depends_on:
            db:
                condition: service_healthy
        hostname: scheduleBot-bot
        restart: always
        environment:
            DISCORD_BOT_TOKEN: '${DISCORD_BOT_TOKEN}'
            DISCORD_EVENT_ROLE_PREFIX: '${DISCORD_EVENT_ROLE_PREFIX}'
            MYSQL_SERVER: '${MYSQL_SERVER}' # optional (Default: scheduleBot-db)
            MYSQL_DATABASE: '${MYSQL_DB}' # optional (Default: ScheduleBot)
            MYSQL_USER: '${MYSQL_USER}' # optional (Default: scheduleBot)
            MYSQL_PASSWORD: '${MYSQL_USER_PW}' # optional (Default: scheduleBot)
        image: 'duinrahaic/schedulebot:latest'
        networks:
            - scheduleBot-network
        env_file:
            - .env
volumes:
  db:
    driver: local
networks:
    scheduleBot-network:
        internal: false
        driver: bridge
        name: scheduleBot-network`
